-- O schema do banco agora mora em supabase/migrations/.
-- Para criar as tabelas no seu projeto: Supabase Dashboard → SQL Editor →
-- cole o conteúdo de supabase/migrations/20261003170000_pontofit_inicial.sql → Run.
